language: python
python:
  - "3.8"
install:
  - pip install PyYAML
  - pip install flexmock
  - pip install pytest-cov coveralls
  - pip install -r tests/requirements.txt
script: py.test -vv -rs tests --cov journal_brief --benchmark-skip
sudo: false
notifications:
  email: false
after_success: "coveralls"
